### ISSUE TITLE
有时自动化部署不成功

### ISSUE THREAD

**Issue by perfectSymphony** [jenkey2011/vuepress-deploy-demo#33]
使用vuepress-deploy这个包实现自动化部署有时候莫名的无法自动化部署，然后又找不到是哪的问题

**Comment by perfectSymphony** [comment]
Initialized empty Git repository in /github/workspace/docs/.vuepress/dist/.git/
fatal: not in a git directory，自动化部署的时候这次又报个这个错误

**Comment by v-laughing** [comment]
> 

我最近也遇到这个问题，你找到原因了吗？

**Comment by perfectSymphony** [comment]
> 

这个有bug，换一个吧
